# Site settings
title: Edo Airoldi
email: airoldi@temple.edu
description: > # this means to ignore newlines until "baseurl:"
  Millard E. Gladfelter Professor of Statistics & Data Science, Professor of Finance (by courtesy), Co-Director of the Temple Data Science Institute, Fox School of Business, Temple University
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mariospapamix.github.io" # the base hostname & protocol for your site
google_scholar_id: XKCyZk0AAAAJ&hl
arxiv_url:  "https://arxiv.org/a/airoldi_e_1"
wiki_url:  "https://en.wikipedia.org/wiki/Edoardo_Airoldi"
# github_username:  airoldi
# twitter_username:  eairoldi
# orchid_id:  0000-0002-3512-0542

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
jobtitle: "Department of Statistical Science\
           Fox School of Business, Temple University\
           1810 Liacouras Walk\
           Philadelphia, PA 19122, USA"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
